apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: "{{ .Release.Name }}-deno-ingress"
    annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
    rules:
        - host: deno.minikube
          http:
              paths:
                  - path: "/{{ .Release.Name }}-" #chemin+nom projet
                    pathType: Prefix
                    backend:
                        service:
                            name: "{{ .Release.Name }}-{{ .Values.web.service.name }}"
                            port:
                                number: 8080
