apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        deployment.kubernetes.io/revision: "3"
    labels:
        app: maria-db
    name: maria-db
    namespace: default
spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
        matchLabels:
            app: maria-db
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: maria-db
        spec:
            containers:
                - image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag | default .Chart.AppVersion }}"
                  imagePullPolicy: {{ .Values.db.image.pullPolicy }}
                  name: maria-db
                  resources: { }
                  env:
                      - name: MARIADB_ROOT_PASSWORD
                        valueFrom:
                             secretKeyRef:
                                 name: mariadb-secret
                                 key: rootPassword
                      - name: MARIADB_DATABASE
                        valueFrom:
                             secretKeyRef:
                                 name: mariadb-secret
                                 key: db
                      - name: MARIADB_USER
                        valueFrom:
                             secretKeyRef:
                                 name: mariadb-secret
                                 key: username
                      - name: MARIADB_PASSWORD
                        valueFrom:
                             secretKeyRef:
                                 name: mariadb-secret
                                 key: password
                  ports:
                      - containerPort: {{ .Values.db.service.port }}
                        name: {{ .Values.db.service.name }}
                  volumeMounts:
                      - name: {{ .Values.db.volumeMounts.name }}
                        mountPath: {{ .Values.db.volumeMounts.mountPath }}
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: { }
            terminationGracePeriodSeconds: 30
            volumes:
                - name: {{ .Values.db.volumes.name }}
                  persistentVolumeClaim:
                      claimName: {{ .Values.db.volumes.claimName }}

---
apiVersion: v1
kind: Service
metadata:
    name: maria-db
spec:
    ports:
        - port: {{ .Values.db.service.port }}
    selector:
        app: maria-db