apiVersion: apps/v1
kind: StatefulSet
metadata:
    labels:
        app: maria-db
    namespace: default
    name: "{{ .Release.Name }}-maria-db"
spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
        matchLabels:
            app: maria-db
    serviceName: "{{ .Release.Name }}-maria-db"
    template:
        metadata:
            labels:
                app: maria-db
        spec:
            containers:
                - image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag | default .Chart.AppVersion }}"
                  imagePullPolicy: {{ .Values.db.image.pullPolicy }}
                  name: "{{ .Release.Name }}-maria-db"
                  resources: { }
                  env:
                      - name: MARIADB_ROOT_PASSWORD
                        valueFrom:
                             secretKeyRef:
                                 name: "{{ .Release.Name }}-mariadb-secret"
                                 key: rootPassword
                      - name: MARIADB_DATABASE
                        valueFrom:
                             secretKeyRef:
                                 name: "{{ .Release.Name }}-mariadb-secret"
                                 key: db
                      - name: MARIADB_USER
                        valueFrom:
                             secretKeyRef:
                                 name: "{{ .Release.Name }}-mariadb-secret"
                                 key: username
                      - name: MARIADB_PASSWORD
                        valueFrom:
                             secretKeyRef:
                                 name: "{{ .Release.Name }}-mariadb-secret"
                                 key: password
                  ports:
                      - containerPort: {{ .Values.db.service.port }}
                        name: "{{ .Release.Name }}-{{ .Values.db.service.name }}"
                  volumeMounts:
                      - name: "{{ .Release.Name }}-{{ .Values.db.volumeMounts.name }}"
                        mountPath: {{ .Values.db.volumeMounts.mountPath }}
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: { }
            terminationGracePeriodSeconds: 30
    volumeClaimTemplates:
        - metadata:
              name: "{{ .Release.Name }}-{{ .Values.db.volumes.name }}"
          spec:
              accessModes: [ "ReadWriteOnce" ]
              resources:
                  requests:
                      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
    name: "{{ .Release.Name }}-maria-db"
spec:
    ports:
        - port: {{ .Values.db.service.port }}
    selector:
        app: maria-db

